version: "3.9"  # recommended latest version

services:
  node-app:
    build: .
    container_name: node-app
    ports:
      - "2000:3000"   # map host 
    environment:
      NODE_ENV: production
    restart: unless-stopped
